# Generated by Django 3.2.4 on 2021-07-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210613_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=100)),
                ('s_id', models.CharField(max_length=100)),
                ('nowpoint', models.IntegerField(default=0, max_length=100)),
                ('h_date', models.CharField(max_length=100)),
            ],
        ),
    ]
